### ISSUE TITLE
add to awesome-yazi

### ISSUE THREAD

**Issue by AnirudhG07** [BBOOXX/file-actions.yazi#1]
Hi! Cool plugin. 
Would you like to add it to [awesome-yazi](https://github.com/AnirudhG07/awesome-yazi)? It would be a great addition among other plugins!

Thanks!

**Comment by BBOOXX** [comment]
Hi!
Thank you for your kind words. I would be happy to add my plugin to awesome-yazi. Please let me know the steps I need to follow to make this happen.

Thanks again!

**Comment by AnirudhG07** [comment]
Hi, it's easy, just see previous PR's. Add it at the bottom of file-action based plugins, mention name, link and small description like other plugins and make the PR. If any changes will be required, I'll make it.
Thanks!

**Comment by BBOOXX** [comment]
Hi, Thank you for the instructions. I just tested the plugin with the latest 0.3 update of yazi, and it broke due to API changes. 😢 I will fix it and submit the PR afterward.

**Comment by AnirudhG07** [comment]
Yeah don't worry. Whenever u feel comfortable sharing the plugin, you are very welcome to do so. If u have any other plugins too, u can add them too.

Looking forward to seeing your plugin!

**Comment by AnirudhG07** [comment]
@BBOOXX Does this support for new v0.3.1 now? I am facing some need of this plugin. Like I want to zip each file in my directory seperately. so I think this would be useful there.

**Comment by BBOOXX** [comment]
@AnirudhG07  Yes, the plugin supports the new version v0.3.1. The script for zipping each file separately is already included in the presets of the plugin. You can find it there and start using it right away. Hope you find it helpful and have fun using it!

**Comment by AnirudhG07** [comment]
HI, it is not working for me!
I am using MacOS, yazi v0.3.1.
You can refer my [dotfiles](https://github.com/AnirudhG07/dotfiles/tree/stow/yazi/.config/yazi/plugins/file-actions.yazi) if required.

When I select all files, and press "f","a" (my keybinding), it shows up in `Task` but doesn't work.

**Comment by AnirudhG07** [comment]
Also can you add it awesome-yazi now? it would be really nice to have this plugin there.

**Comment by BBOOXX** [comment]
Hi @AnirudhG07 

Thank you for your feedback! I reviewed your dotconfig for Yazi and noticed that file-actions was not included in the keymap.toml. After I added it to the keymap, everything works as expected.

I'm also using macOS with Yazi version 0.3.1 (Homebrew 2024-08-15), and it functions correctly on my end.

I agree with your suggestion to add this plugin to awesome-yazi.

Thanks again for your support, and feel free to reach out if you have any other questions or issues!

Regarding the keymap.toml , here’s the addition I made:
```
[[manager.prepend_keymap]]
on = [ "f" ,"a"]
run = "plugin file-actions --args='around '"
desc= "Perform actions on selected files"
```

**Comment by AnirudhG07** [comment]
Oops. I forgot to push the keymap to the dotfiles. I copy pasted ur keymap(although it didnt change anything).
Here is how I am using file-actions.yazi, please correct me
1) I select all files with <C-a> and then pressed "f","a"
Nothing worked
2) I selected and yanked all files(since demo has them yanked ig), then pressed "f","a". it didnt work.

Here is my yazi --debug. Please see.
```

Yazi
    Version: 0.3.1 (99a3b3a 2024-08-17)
    Debug  : false
    OS     : macos-aarch64 (unix)

Ya
    Version: 0.3.1 (99a3b3a 2024-08-17)

Emulator
    Emulator.via_env: ("xterm-256color", "iTerm.app")
    Emulator.via_csi: Ok(Iterm2)
    Emulator.detect : Iterm2

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.6


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/Users/anirudhgupta/.local/state/yazi" directory.
```

**Comment by BBOOXX** [comment]
🤔 The plugin will act on the files or folders you've selected. If nothing is selected, it defaults to the file or folder where your cursor is. I just updated to the latest version using brew install yazi --HEAD and used the yazi configuration from your dotfile, and everything is running smoothly on my end. I’ve attached a video to show you how it works. Hope this helps!


https://github.com/user-attachments/assets/e548d304-c8d3-4d70-98ee-2d528ee7407b

**Comment by AnirudhG07** [comment]
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/44014954-db8c-42e9-8516-32a5667b907e">
It just stops here for me :<
I think it's not the plugin's issue. Something from my end is not working. Today I added 2 plugins, and the other one strangely doesnt work either. must be some other issues. Ill check

**Comment by AnirudhG07** [comment]
Yes I fixed the issue. It was on my end only. Not urs.
Sorry for the TROUBLE!!!

Hope to see file-actions in awesome-yazi soon.

**Comment by BBOOXX** [comment]
Thank you for confirming that the issue was on your end. No worries at all! I'm glad it got resolved. 😉
