### ISSUE TITLE
Add LICENCE

### ISSUE THREAD

**Issue by AnirudhG07** [BBOOXX/file-actions.yazi#2]
Hi, pls add some LICENSE file, else this plugin won't be able to be downloaded using `ya pack`.

Tip: 
1) almost every plugin uses MIT, so why not.
2) add to readme, `ya pack -a BBOOXX/file-actions`, to be able to download it using `ya pack`

Thanks!

**Comment by BBOOXX** [comment]
Hi! Thanks for the heads up. I've added the MIT LICENSE to the project now.  😉

**Comment by AnirudhG07** [comment]
Yeah now it's downloadable by `ya pack`, although unlike git clone, you dont get premade `actions` folder by itself, you ll have to manually download it. I think thats `ya pack`'s features maybe to avoid possibly unneeded files in SOME plugins.

Anyways thanks, you can add to readme too if you like. 
Cheers
