### ISSUE TITLE
compressing each file has a bug

### ISSUE THREAD

**Issue by AnirudhG07** [BBOOXX/file-actions.yazi#3]
When i have many folders and i want to compress each folder into a zip, the below issue happens.

[Screencast from 27-09-24 03:17:21 PM IST.webm](https://github.com/user-attachments/assets/eba90cc2-07de-4e9c-80cf-68702563145c)

The issue is that anything after `.` is cut.
See that "mistral7B_0", the decimal and after got deleted.
please fix this.

**Comment by BBOOXX** [comment]
I have updated the script to ensure that file suffixes are only removed for files, not directories. 
Thanks for bringing this up! 😉

**Comment by AnirudhG07** [comment]
Yep now it works just fine! Thanks so much!
Do check just in case if any other pre-made actions of yours might face this.

Thanks!
